# Generated by Django 3.2.4 on 2022-04-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='', upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='img',
        ),
    ]
